max_width = 100
use_small_heuristics = "Max"
merge_derives = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_impl_items = true
wrap_comments = true 